/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole__1 = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const BloodGroup = IDL.Variant({
  'aNegative' : IDL.Null,
  'oPositive' : IDL.Null,
  'abPositive' : IDL.Null,
  'bPositive' : IDL.Null,
  'aPositive' : IDL.Null,
  'oNegative' : IDL.Null,
  'abNegative' : IDL.Null,
  'bNegative' : IDL.Null,
});
export const Time = IDL.Int;
export const EmergencyRequest = IDL.Record({
  'hospital' : IDL.Text,
  'requester' : IDL.Principal,
  'contactName' : IDL.Text,
  'isActive' : IDL.Bool,
  'bloodGroup' : BloodGroup,
  'timestamp' : Time,
  'units' : IDL.Nat,
  'contactPhone' : IDL.Text,
});
export const UserRole = IDL.Variant({
  'both' : IDL.Null,
  'recipient' : IDL.Null,
  'donor' : IDL.Null,
});
export const UserProfile = IDL.Record({
  'isMobilePublic' : IDL.Bool,
  'city' : IDL.Text,
  'role' : UserRole,
  'universityId' : IDL.Text,
  'fullName' : IDL.Text,
  'mobileNumber' : IDL.Text,
  'isVerified' : IDL.Bool,
  'bloodGroup' : BloodGroup,
  'lastDonation' : IDL.Opt(Time),
  'donationCount' : IDL.Nat,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
  'confirmDonation' : IDL.Func([IDL.Principal], [], []),
  'createEmergencyRequest' : IDL.Func([EmergencyRequest], [IDL.Nat], []),
  'deactivateEmergencyRequest' : IDL.Func([IDL.Nat], [], []),
  'getActiveRequests' : IDL.Func([], [IDL.Vec(EmergencyRequest)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'searchDonors' : IDL.Func(
      [IDL.Opt(BloodGroup), IDL.Opt(IDL.Text)],
      [IDL.Vec(UserProfile)],
      ['query'],
    ),
  'updateEmergencyRequest' : IDL.Func([IDL.Nat, EmergencyRequest], [], []),
  'verifyDonor' : IDL.Func([IDL.Principal], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole__1 = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const BloodGroup = IDL.Variant({
    'aNegative' : IDL.Null,
    'oPositive' : IDL.Null,
    'abPositive' : IDL.Null,
    'bPositive' : IDL.Null,
    'aPositive' : IDL.Null,
    'oNegative' : IDL.Null,
    'abNegative' : IDL.Null,
    'bNegative' : IDL.Null,
  });
  const Time = IDL.Int;
  const EmergencyRequest = IDL.Record({
    'hospital' : IDL.Text,
    'requester' : IDL.Principal,
    'contactName' : IDL.Text,
    'isActive' : IDL.Bool,
    'bloodGroup' : BloodGroup,
    'timestamp' : Time,
    'units' : IDL.Nat,
    'contactPhone' : IDL.Text,
  });
  const UserRole = IDL.Variant({
    'both' : IDL.Null,
    'recipient' : IDL.Null,
    'donor' : IDL.Null,
  });
  const UserProfile = IDL.Record({
    'isMobilePublic' : IDL.Bool,
    'city' : IDL.Text,
    'role' : UserRole,
    'universityId' : IDL.Text,
    'fullName' : IDL.Text,
    'mobileNumber' : IDL.Text,
    'isVerified' : IDL.Bool,
    'bloodGroup' : BloodGroup,
    'lastDonation' : IDL.Opt(Time),
    'donationCount' : IDL.Nat,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole__1], [], []),
    'confirmDonation' : IDL.Func([IDL.Principal], [], []),
    'createEmergencyRequest' : IDL.Func([EmergencyRequest], [IDL.Nat], []),
    'deactivateEmergencyRequest' : IDL.Func([IDL.Nat], [], []),
    'getActiveRequests' : IDL.Func([], [IDL.Vec(EmergencyRequest)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole__1], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'searchDonors' : IDL.Func(
        [IDL.Opt(BloodGroup), IDL.Opt(IDL.Text)],
        [IDL.Vec(UserProfile)],
        ['query'],
      ),
    'updateEmergencyRequest' : IDL.Func([IDL.Nat, EmergencyRequest], [], []),
    'verifyDonor' : IDL.Func([IDL.Principal], [], []),
  });
};

export const init = ({ IDL }) => { return []; };