/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type BloodGroup = { 'aNegative' : null } |
  { 'oPositive' : null } |
  { 'abPositive' : null } |
  { 'bPositive' : null } |
  { 'aPositive' : null } |
  { 'oNegative' : null } |
  { 'abNegative' : null } |
  { 'bNegative' : null };
export interface EmergencyRequest {
  'hospital' : string,
  'requester' : Principal,
  'contactName' : string,
  'isActive' : boolean,
  'bloodGroup' : BloodGroup,
  'timestamp' : Time,
  'units' : bigint,
  'contactPhone' : string,
}
export type Time = bigint;
export interface UserProfile {
  'isMobilePublic' : boolean,
  'city' : string,
  'role' : UserRole,
  'universityId' : string,
  'fullName' : string,
  'mobileNumber' : string,
  'isVerified' : boolean,
  'bloodGroup' : BloodGroup,
  'lastDonation' : [] | [Time],
  'donationCount' : bigint,
}
export type UserRole = { 'both' : null } |
  { 'recipient' : null } |
  { 'donor' : null };
export type UserRole__1 = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole__1], undefined>,
  'confirmDonation' : ActorMethod<[Principal], undefined>,
  'createEmergencyRequest' : ActorMethod<[EmergencyRequest], bigint>,
  'deactivateEmergencyRequest' : ActorMethod<[bigint], undefined>,
  'getActiveRequests' : ActorMethod<[], Array<EmergencyRequest>>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole__1>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'searchDonors' : ActorMethod<
    [[] | [BloodGroup], [] | [string]],
    Array<UserProfile>
  >,
  'updateEmergencyRequest' : ActorMethod<[bigint, EmergencyRequest], undefined>,
  'verifyDonor' : ActorMethod<[Principal], undefined>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];