/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export type Time = bigint;
export interface EmergencyRequest {
    hospital: string;
    requester: Principal;
    contactName: string;
    isActive: boolean;
    bloodGroup: BloodGroup;
    timestamp: Time;
    units: bigint;
    contactPhone: string;
}
export interface UserProfile {
    isMobilePublic: boolean;
    city: string;
    role: UserRole;
    universityId: string;
    fullName: string;
    mobileNumber: string;
    isVerified: boolean;
    bloodGroup: BloodGroup;
    lastDonation?: Time;
    donationCount: bigint;
}
export enum BloodGroup {
    aNegative = "aNegative",
    oPositive = "oPositive",
    abPositive = "abPositive",
    bPositive = "bPositive",
    aPositive = "aPositive",
    oNegative = "oNegative",
    abNegative = "abNegative",
    bNegative = "bNegative"
}
export enum UserRole {
    both = "both",
    recipient = "recipient",
    donor = "donor"
}
export enum UserRole__1 {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole__1): Promise<void>;
    confirmDonation(donor: Principal): Promise<void>;
    createEmergencyRequest(request: EmergencyRequest): Promise<bigint>;
    deactivateEmergencyRequest(id: bigint): Promise<void>;
    getActiveRequests(): Promise<Array<EmergencyRequest>>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole__1>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    searchDonors(bloodGroup: BloodGroup | null, city: string | null): Promise<Array<UserProfile>>;
    updateEmergencyRequest(id: bigint, request: EmergencyRequest): Promise<void>;
    verifyDonor(user: Principal): Promise<void>;
}
import type { BloodGroup as _BloodGroup, EmergencyRequest as _EmergencyRequest, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole, UserRole__1 as _UserRole__1 } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole__1): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole__1_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async confirmDonation(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.confirmDonation(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.confirmDonation(arg0);
            return result;
        }
    }
    async createEmergencyRequest(arg0: EmergencyRequest): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createEmergencyRequest(to_candid_EmergencyRequest_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createEmergencyRequest(to_candid_EmergencyRequest_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async deactivateEmergencyRequest(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deactivateEmergencyRequest(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deactivateEmergencyRequest(arg0);
            return result;
        }
    }
    async getActiveRequests(): Promise<Array<EmergencyRequest>> {
        if (this.processError) {
            try {
                const result = await this.actor.getActiveRequests();
                return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getActiveRequests();
            return from_candid_vec_n7(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole__1> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole__1_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole__1_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(to_candid_UserProfile_n20(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async searchDonors(arg0: BloodGroup | null, arg1: string | null): Promise<Array<UserProfile>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchDonors(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1));
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchDonors(to_candid_opt_n24(this._uploadFile, this._downloadFile, arg0), to_candid_opt_n25(this._uploadFile, this._downloadFile, arg1));
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateEmergencyRequest(arg0: bigint, arg1: EmergencyRequest): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateEmergencyRequest(arg0, to_candid_EmergencyRequest_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateEmergencyRequest(arg0, to_candid_EmergencyRequest_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async verifyDonor(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.verifyDonor(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.verifyDonor(arg0);
            return result;
        }
    }
}
function from_candid_BloodGroup_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BloodGroup): BloodGroup {
    return from_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function from_candid_EmergencyRequest_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _EmergencyRequest): EmergencyRequest {
    return from_candid_record_n9(_uploadFile, _downloadFile, value);
}
function from_candid_UserProfile_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserProfile): UserProfile {
    return from_candid_record_n14(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole__1_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole__1): UserRole__1 {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n16(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : from_candid_UserProfile_n13(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Time]): Time | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isMobilePublic: boolean;
    city: string;
    role: _UserRole;
    universityId: string;
    fullName: string;
    mobileNumber: string;
    isVerified: boolean;
    bloodGroup: _BloodGroup;
    lastDonation: [] | [_Time];
    donationCount: bigint;
}): {
    isMobilePublic: boolean;
    city: string;
    role: UserRole;
    universityId: string;
    fullName: string;
    mobileNumber: string;
    isVerified: boolean;
    bloodGroup: BloodGroup;
    lastDonation?: Time;
    donationCount: bigint;
} {
    return {
        isMobilePublic: value.isMobilePublic,
        city: value.city,
        role: from_candid_UserRole_n15(_uploadFile, _downloadFile, value.role),
        universityId: value.universityId,
        fullName: value.fullName,
        mobileNumber: value.mobileNumber,
        isVerified: value.isVerified,
        bloodGroup: from_candid_BloodGroup_n10(_uploadFile, _downloadFile, value.bloodGroup),
        lastDonation: record_opt_to_undefined(from_candid_opt_n17(_uploadFile, _downloadFile, value.lastDonation)),
        donationCount: value.donationCount
    };
}
function from_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hospital: string;
    requester: Principal;
    contactName: string;
    isActive: boolean;
    bloodGroup: _BloodGroup;
    timestamp: _Time;
    units: bigint;
    contactPhone: string;
}): {
    hospital: string;
    requester: Principal;
    contactName: string;
    isActive: boolean;
    bloodGroup: BloodGroup;
    timestamp: Time;
    units: bigint;
    contactPhone: string;
} {
    return {
        hospital: value.hospital,
        requester: value.requester,
        contactName: value.contactName,
        isActive: value.isActive,
        bloodGroup: from_candid_BloodGroup_n10(_uploadFile, _downloadFile, value.bloodGroup),
        timestamp: value.timestamp,
        units: value.units,
        contactPhone: value.contactPhone
    };
}
function from_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aNegative: null;
} | {
    oPositive: null;
} | {
    abPositive: null;
} | {
    bPositive: null;
} | {
    aPositive: null;
} | {
    oNegative: null;
} | {
    abNegative: null;
} | {
    bNegative: null;
}): BloodGroup {
    return "aNegative" in value ? BloodGroup.aNegative : "oPositive" in value ? BloodGroup.oPositive : "abPositive" in value ? BloodGroup.abPositive : "bPositive" in value ? BloodGroup.bPositive : "aPositive" in value ? BloodGroup.aPositive : "oNegative" in value ? BloodGroup.oNegative : "abNegative" in value ? BloodGroup.abNegative : "bNegative" in value ? BloodGroup.bNegative : value;
}
function from_candid_variant_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    both: null;
} | {
    recipient: null;
} | {
    donor: null;
}): UserRole {
    return "both" in value ? UserRole.both : "recipient" in value ? UserRole.recipient : "donor" in value ? UserRole.donor : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole__1 {
    return "admin" in value ? UserRole__1.admin : "user" in value ? UserRole__1.user : "guest" in value ? UserRole__1.guest : value;
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserProfile>): Array<UserProfile> {
    return value.map((x)=>from_candid_UserProfile_n13(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_EmergencyRequest>): Array<EmergencyRequest> {
    return value.map((x)=>from_candid_EmergencyRequest_n8(_uploadFile, _downloadFile, x));
}
function to_candid_BloodGroup_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): _BloodGroup {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_EmergencyRequest_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: EmergencyRequest): _EmergencyRequest {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserProfile_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserProfile): _UserProfile {
    return to_candid_record_n21(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole__1_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): _UserRole__1 {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_opt_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup | null): [] | [_BloodGroup] {
    return value === null ? candid_none() : candid_some(to_candid_BloodGroup_n5(_uploadFile, _downloadFile, value));
}
function to_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: string | null): [] | [string] {
    return value === null ? candid_none() : candid_some(value);
}
function to_candid_record_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    isMobilePublic: boolean;
    city: string;
    role: UserRole;
    universityId: string;
    fullName: string;
    mobileNumber: string;
    isVerified: boolean;
    bloodGroup: BloodGroup;
    lastDonation?: Time;
    donationCount: bigint;
}): {
    isMobilePublic: boolean;
    city: string;
    role: _UserRole;
    universityId: string;
    fullName: string;
    mobileNumber: string;
    isVerified: boolean;
    bloodGroup: _BloodGroup;
    lastDonation: [] | [_Time];
    donationCount: bigint;
} {
    return {
        isMobilePublic: value.isMobilePublic,
        city: value.city,
        role: to_candid_UserRole_n22(_uploadFile, _downloadFile, value.role),
        universityId: value.universityId,
        fullName: value.fullName,
        mobileNumber: value.mobileNumber,
        isVerified: value.isVerified,
        bloodGroup: to_candid_BloodGroup_n5(_uploadFile, _downloadFile, value.bloodGroup),
        lastDonation: value.lastDonation ? candid_some(value.lastDonation) : candid_none(),
        donationCount: value.donationCount
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    hospital: string;
    requester: Principal;
    contactName: string;
    isActive: boolean;
    bloodGroup: BloodGroup;
    timestamp: Time;
    units: bigint;
    contactPhone: string;
}): {
    hospital: string;
    requester: Principal;
    contactName: string;
    isActive: boolean;
    bloodGroup: _BloodGroup;
    timestamp: _Time;
    units: bigint;
    contactPhone: string;
} {
    return {
        hospital: value.hospital,
        requester: value.requester,
        contactName: value.contactName,
        isActive: value.isActive,
        bloodGroup: to_candid_BloodGroup_n5(_uploadFile, _downloadFile, value.bloodGroup),
        timestamp: value.timestamp,
        units: value.units,
        contactPhone: value.contactPhone
    };
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole__1): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole__1.admin ? {
        admin: null
    } : value == UserRole__1.user ? {
        user: null
    } : value == UserRole__1.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    both: null;
} | {
    recipient: null;
} | {
    donor: null;
} {
    return value == UserRole.both ? {
        both: null
    } : value == UserRole.recipient ? {
        recipient: null
    } : value == UserRole.donor ? {
        donor: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: BloodGroup): {
    aNegative: null;
} | {
    oPositive: null;
} | {
    abPositive: null;
} | {
    bPositive: null;
} | {
    aPositive: null;
} | {
    oNegative: null;
} | {
    abNegative: null;
} | {
    bNegative: null;
} {
    return value == BloodGroup.aNegative ? {
        aNegative: null
    } : value == BloodGroup.oPositive ? {
        oPositive: null
    } : value == BloodGroup.abPositive ? {
        abPositive: null
    } : value == BloodGroup.bPositive ? {
        bPositive: null
    } : value == BloodGroup.aPositive ? {
        aPositive: null
    } : value == BloodGroup.oNegative ? {
        oNegative: null
    } : value == BloodGroup.abNegative ? {
        abNegative: null
    } : value == BloodGroup.bNegative ? {
        bNegative: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
